'use client'

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell,
} from 'recharts'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { useFetchAllRecords } from '@/hooks/use-time-record'
import { CustomTooltip } from './CustomTooltip'
import { DateRange } from 'react-day-picker'
import { Clock, Calendar, TrendingUp, User, Target } from 'lucide-react'

type DashboardRecordsProps = {
  dateRange?: DateRange
}

export const DashboardRecords = ({ dateRange }: DashboardRecordsProps) => {
  const { data, isLoading } = useFetchAllRecords()

  const parseRecordDate = (dateString: string): Date => {
    if (dateString.includes('/')) {
      const [day, month, year] = dateString.split('/')
      return new Date(+year, +month - 1, +day)
    }
    if (dateString.includes('-')) {
      return new Date(dateString)
    }
    return new Date(dateString)
  }

  const getLastValidMonth = () => {
    const validRecordsForMonth = (data ?? [])
      .filter(
        (record) =>
          record.date &&
          record.employee === 'thalia' &&
          !!record.clockIn &&
          !!record.clockOut
      )
      .map((record) => parseRecordDate(record.date))
      .sort((a, b) => b.getTime() - a.getTime())

    if (validRecordsForMonth.length === 0) return null

    const latestDate = validRecordsForMonth[0]
    const year = latestDate.getFullYear()
    const month = latestDate.getMonth()

    const firstDay = new Date(year, month, 1)
    const lastDay = new Date(year, month + 1, 0)

    return { from: firstDay, to: lastDay }
  }

  const effectiveDateRange =
    dateRange?.from || dateRange?.to ? dateRange : getLastValidMonth()

  const filteredData = (data ?? []).filter((record) => {
    if (!record.date) return false
    if (!effectiveDateRange?.from && !effectiveDateRange?.to) return true

    const recordDate = parseRecordDate(record.date)
    const afterFrom = effectiveDateRange?.from
      ? recordDate >= effectiveDateRange.from
      : true
    const beforeTo = effectiveDateRange?.to
      ? recordDate <= effectiveDateRange.to
      : true

    return afterFrom && beforeTo
  })

  const validRecords = (filteredData ?? [])
    .filter(
      (record) =>
        record.employee === 'thalia' && !!record.clockIn && !!record.clockOut
    )
    .map((record) => {
      const clockInDate = new Date(record.clockIn!)
      const clockOutDate = new Date(record.clockOut!)
      const diffMs = clockOutDate.getTime() - clockInDate.getTime()
      const workedHours = Math.max(0, diffMs / (1000 * 60 * 60))

      const recordDate = parseRecordDate(record.date)
      const formattedDate = recordDate.toLocaleDateString('pt-BR', {
        day: '2-digit',
        month: '2-digit',
      })

      return {
        date: formattedDate,
        fullDate: recordDate,
        hours: parseFloat(workedHours.toFixed(2)),
        clockIn: record.clockIn!,
        clockOut: record.clockOut!,
      }
    })
    .sort((a, b) => a.fullDate.getTime() - b.fullDate.getTime())

  const stats = {
    totalHours: validRecords.reduce((sum, record) => sum + record.hours, 0),
    averageHours:
      validRecords.length > 0
        ? validRecords.reduce((sum, record) => sum + record.hours, 0) /
          validRecords.length
        : 0,
    totalDays: validRecords.length,
    maxHours:
      validRecords.length > 0
        ? Math.max(...validRecords.map((r) => r.hours))
        : 0,
    minHours:
      validRecords.length > 0
        ? Math.min(...validRecords.map((r) => r.hours))
        : 0,
  }

  const workingHoursDistribution = [
    {
      name: 'Menos de 6h',
      value: validRecords.filter((r) => r.hours < 6).length,
      color: '#ef4444',
    },
    {
      name: '6h - 8h',
      value: validRecords.filter((r) => r.hours >= 6 && r.hours <= 8).length,
      color: '#3b82f6',
    },
    {
      name: 'Mais de 8h',
      value: validRecords.filter((r) => r.hours > 8).length,
      color: '#10b981',
    },
  ]

  const getTitle = () => {
    const currentRange = effectiveDateRange
    if (!currentRange?.from && !currentRange?.to) {
      return 'Dashboard - Thalia'
    }

    const fromDate = currentRange?.from?.toLocaleDateString('pt-BR')
    const toDate = currentRange?.to?.toLocaleDateString('pt-BR')
    const isAutoGenerated = !dateRange?.from && !dateRange?.to
    const prefix = isAutoGenerated ? 'Último mês - ' : ''

    if (fromDate && toDate) {
      return `${prefix}Dashboard - Thalia (${fromDate} - ${toDate})`
    }
    return 'Dashboard - Thalia'
  }

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {[...Array(4)].map((_, i) => (
            <Card key={i} className="animate-pulse">
              <CardContent className="p-6">
                <div className="h-16 bg-gray-200 rounded"></div>
              </CardContent>
            </Card>
          ))}
        </div>
        <Card className="animate-pulse">
          <CardContent className="p-6">
            <div className="h-96 bg-gray-200 rounded"></div>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2 mb-6">
        <User className="h-6 w-6 text-primary" />
        <h1 className="text-2xl font-bold">{getTitle()}</h1>
      </div>

      {/* Cards de estatísticas */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="bg-gradient-to-br from-blue-50 to-blue-100 border-blue-200">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-blue-600">
                  Total de Horas
                </p>
                <p className="text-2xl font-bold text-blue-900">
                  {stats.totalHours.toFixed(1)}h
                </p>
              </div>
              <Clock className="h-8 w-8 text-blue-500" />
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-green-50 to-green-100 border-green-200">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-green-600">
                  Média Diária
                </p>
                <p className="text-2xl font-bold text-green-900">
                  {stats.averageHours.toFixed(1)}h
                </p>
              </div>
              <TrendingUp className="h-8 w-8 text-green-500" />
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-purple-50 to-purple-100 border-purple-200">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-purple-600">
                  Dias Trabalhados
                </p>
                <p className="text-2xl font-bold text-purple-900">
                  {stats.totalDays}
                </p>
              </div>
              <Calendar className="h-8 w-8 text-purple-500" />
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-orange-50 to-orange-100 border-orange-200">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-orange-600">
                  Meta 8h/dia
                </p>
                <p className="text-2xl font-bold text-orange-900">
                  {((stats.averageHours / 8) * 100).toFixed(0)}%
                </p>
              </div>
              <Target className="h-8 w-8 text-orange-500" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Gráficos */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Gráfico de barras principal */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle className="text-lg">Horas Trabalhadas por Dia</CardTitle>
          </CardHeader>
          <CardContent>
            {validRecords.length > 0 ? (
              <ResponsiveContainer width="100%" height={350}>
                <BarChart
                  data={validRecords}
                  margin={{ top: 20, right: 30, left: 20, bottom: 60 }}
                >
                  <XAxis
                    dataKey="date"
                    tick={{ fontSize: 11 }}
                    interval="preserveStartEnd"
                    angle={-30}
                    textAnchor="end"
                    height={60}
                  />
                  <YAxis
                    label={{
                      value: 'Horas',
                      angle: -90,
                      position: 'insideLeft',
                      style: { textAnchor: 'middle', fontSize: 12 },
                    }}
                  />
                  <Tooltip content={<CustomTooltip />} />
                  <Bar
                    dataKey="hours"
                    fill="#3b82f6"
                    radius={[4, 4, 0, 0]}
                    name="Horas"
                  />
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <div className="flex items-center justify-center h-[350px] text-muted-foreground">
                Nenhum registro encontrado
              </div>
            )}
          </CardContent>
        </Card>

        {/* Gráfico de pizza */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Distribuição de Horas</CardTitle>
          </CardHeader>
          <CardContent>
            {validRecords.length > 0 ? (
              <ResponsiveContainer width="100%" height={350}>
                <PieChart>
                  <Pie
                    data={workingHoursDistribution}
                    cx="50%"
                    cy="50%"
                    innerRadius={60}
                    outerRadius={120}
                    paddingAngle={5}
                    dataKey="value"
                  >
                    {workingHoursDistribution.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip
                    formatter={(value, name) => [`${value} dias`, name]}
                  />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <div className="flex items-center justify-center h-[350px] text-muted-foreground">
                Sem dados disponíveis
              </div>
            )}
            <div className="mt-4 space-y-2">
              {workingHoursDistribution.map((item, index) => (
                <div key={index} className="flex items-center gap-2">
                  <div
                    className="w-3 h-3 rounded-full"
                    style={{ backgroundColor: item.color }}
                  />
                  <span className="text-sm">
                    {item.name}: {item.value} dias
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Gráfico de linha para tendência */}
      {validRecords.length > 5 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">
              Tendência de Horas Trabalhadas
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <LineChart
                data={validRecords}
                margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
              >
                <XAxis
                  dataKey="date"
                  tick={{ fontSize: 11 }}
                  interval="preserveStartEnd"
                />
                <YAxis
                  label={{
                    value: 'Horas',
                    angle: -90,
                    position: 'insideLeft',
                    style: { textAnchor: 'middle', fontSize: 12 },
                  }}
                />
                <Tooltip content={<CustomTooltip />} />
                <Line
                  type="monotone"
                  dataKey="hours"
                  stroke="#3b82f6"
                  strokeWidth={2}
                  dot={{ fill: '#3b82f6', strokeWidth: 2, r: 4 }}
                  activeDot={{ r: 6 }}
                />
              </LineChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
